USE [master]
GO

/****** Object:  Database [DoAnWeb]    Script Date: 25/06/2021 10:49:25 ******/
CREATE DATABASE [DoAnWeb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DoAnWeb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER20171\MSSQL\DATA\DoAnWeb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DoAnWeb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER20171\MSSQL\DATA\DoAnWeb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DoAnWeb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DoAnWeb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DoAnWeb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DoAnWeb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DoAnWeb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DoAnWeb] SET ARITHABORT OFF 
GO

ALTER DATABASE [DoAnWeb] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [DoAnWeb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DoAnWeb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DoAnWeb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DoAnWeb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DoAnWeb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DoAnWeb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DoAnWeb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DoAnWeb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DoAnWeb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DoAnWeb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DoAnWeb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DoAnWeb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DoAnWeb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DoAnWeb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DoAnWeb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DoAnWeb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DoAnWeb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DoAnWeb] SET  MULTI_USER 
GO

ALTER DATABASE [DoAnWeb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DoAnWeb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DoAnWeb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DoAnWeb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DoAnWeb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DoAnWeb] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DoAnWeb] SET  READ_WRITE 
GO


